name: Publish Swift Package

on:
  workflow_dispatch:
  push:
    [main]
permissions:
  contents: write
  packages: write

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.8